# Generated by Django 4.2.1 on 2025-04-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0012_remove_auctionuser_adhar_card_and_more'),
        ('bid_app', '0014_product_comment'),
    ]

    operations = [
    ]
