# Generated by Django 4.2.1 on 2025-04-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0017_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
